# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - tvent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'
          
      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: set up environment variables
        run: |
          echo "APP_URL=https://tvent.azurewebsites.net" >> .env
          echo "APP_KEY=" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "ASSET_URL=https://tvent.azurewebsites.net" >> .env
          echo "BROADCAST_DRIVER=pusher" >> .env.testing
          echo "PUSHER_APP_ID=${{ secrets.PUSHER_APP_ID }}" >> .env.testing
          echo "PUSHER_APP_KEY=${{ secrets.PUSHER_APP_KEY }}" >> .env.testing
          echo "PUSHER_APP_SECRET=${{ secrets.PUSHER_APP_SECRET }}" >> .env.testing
          echo "PUSHER_APP_CLUSTER=${{ secrets.PUSHER_APP_CLUSTER }}" >> .env.testing

      - name: set up testing environment variables
        run: |
          echo "DB_CONNECTION=mysql" >> .env.testing
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.testing
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env.testing
          echo "DB_DATABASE=testing" >> .env.testing
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env.testing
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.testing

      - name: test
        run: php artisan test --env=testing
        
      - name: generate key
        run: php artisan key:generate

      - name: run migrations
        run: php artisan migrate --force

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'tvent'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9C65BF99A9954E15B3E849350DC59BF6 }}